<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Just Dance(ability)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">TEAM NAME</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data">Introduction and data</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review">Literature Review</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#results-and-analysis" id="toc-results-and-analysis" class="nav-link" data-scroll-target="#results-and-analysis">Results and Analysis</a></li>
  <li><a href="#overall-results-next-steps-limitations-discussion" id="toc-overall-results-next-steps-limitations-discussion" class="nav-link" data-scroll-target="#overall-results-next-steps-limitations-discussion">Overall Results + Next Steps + Limitations (DISCUSSION)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Just Dance(ability)</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction-and-data" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-data">Introduction and data</h2>
<p>Within the music industry there is always a desire to be able to predict the next big song. Different factors will always play into whether or not a song becomes popular. We wish to explore how danceability, in particular, affects the popularity of songs. To dig a bit deeper, we want to see if the impact of danceability on popularity changes depending on which genre we are exploring. We are hoping that by exploring this correlation we can create a predictive model for popularity based on danceability. Based on the correlations we find by genre this model may be more accurate for certain genres more so than others. We have three research questions: How does danceability affect the popularity of songs? How does this vary between genres? How do other song variables influence this relationship.</p>
<p>Our research project will center around the Spotifyr, an open source music dataset provided by Spotify. The dataset contains around 5,000 songs from six major music categories (EDM, Latin, Pop, R&amp;B, Rap, and Rock). These genres were selected from Every Noise, which is a visualization created and maintained by a genre taxonomist. The top four genre’s from Every Noise were used to find 20 playlists that contained relevant songs. The 5000 songs from these playlists were added to the dataset that we are analyzing. This data was gathered for a tidytuesday podcast. For each song, the data set contains general information such as the songs album, artist, release data, but also more interesting statistics on danceability, energy, and popularity. The Spotify Web API was used to gain information about the songs. Spotify has twelve different features that are associated with songs. These are included within the dataset as variables.</p>
<p>We considered different ethical questions surrounding data collection. Specifically, we explored how songs were chosen from Spotify and acquisition bias; however, do not believe there are significant ethical concerns related to this data and data collection.</p>
<p>We hypothesize that there will be a positive correlation between danceability and popularity, but that correlation will differ between genres. We expect the Latin genre to have the greatest correlation. Additionally, we hypothesize that the tempo and the energy of the song (when taken into consideration with the danceability rating) will better be able to predict track popularity rating.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">Literature Review</h2>
<p>Our data set was originally found through the #tidytuesday project on GitHub. Kaylin Pavlik, a blogger, explored this dataset in various ways. She explored audio features by genre. She found that EDM tracks are the least likely to have acoustic features, but highly likely to have high energy with low valence. Additionally, through density/line plots, she found that danceability, tempo, valence, and energy had the largest differences by genre. We are building on her research by specifically analyzing the differences between danceability by genre. Our research question digs deeper into this question. Additionally, she found that Latin music was very danceable, while rock music had very little danceability. We will continue to look into the specifics of these differences through linear regression models ^[https://www.kaylinpavlik.com/classifying-songs-genres].</p>
<p>Amri Rohman also analyzed this dataset ^[https://rpubs.com/amrirohman/spotify-song]. She specifically looked at songs and their popularity. In 2020 she found that the most popular Spotify song was Dance Monkey. She also looked at the differences in tempo for each genre, faceted by different eras of music. She found that rap songs in the 2000s had slower tempos. We are going to build on these research questions by looking at the popularity of songs by genre faceted by dancability. We are both analyzing how different song features vary across genres.</p>
<p>Although other groups/people have looked into the same Spotifyr datset from tidytuesday, we are planning on looking into vastly different research questions. Because this is a large data set with many variables, there are many questions to look into. We hope to dive into popularity to analyze reasons as to why songs and genres have gained notoriety.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>We plan to answer this research question through a linear regression analysis looking at if the danceability of a song can be predictive for its popularity. This regression analysis will likely consider the energy and tempo variables in the regression analysis. This analysis will be faceted across genres as well. First, we will look to see at the general relationship between danceability rating and track popularity rating of songs in the data. Then, we will look to into the level of this relationship in terms of different types of music by assessing genre as variable. In addition to these basic visualizations, we will also calculate a number of summary statistics that will further assist in other analyses and allow us to better understand the data. This includes calculation of the mean danceability rating and popularity ratings specifically to each genre.</p>
<p>Additionally, we will conduct a regression analysis to predict popularity on the basis of danceability ratings. This linear regression will have additional models looking specifically at Latin and Rap genres as well. There will also be a regression analysis conducted to assess how other variables related to a song influence the relationship between danceability and popularity. The approriate type of regression for this would be a multiple linear regression, taking into consideration multiple explanatory variables to predict track popularity. The specific quantitative variables we want to consider are energy and tempo because of their relation to danceability in this regression analysis as similarly considered by a similar project by Ochi et al.&nbsp;(n.d.). We will assess these types of regressions with both additive and interaction models to see which type of model best fits the data.</p>
<p>To assess these models created, we will conduct calculations for adjusted R-squared and AIC. We used adjusted R-squared rather than r-squared because it takes into account the amount of variables that are being used. We were analyzing different variables in this dataset, so adjusted r-square was a better metric to use. These two metrics were used to determine the best fit model, specifically when using the many variables that we were assessing.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 23
  track_id       track…¹ track…² track…³ track…⁴ track…⁵ track…⁶ playl…⁷ playl…⁸
  &lt;chr&gt;          &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
1 6f807x0ima9a1… I Don'… Ed She…      66 2oCs0D… I Don'… 2019-0… Pop Re… 37i9dQ…
2 0r7CVbZTWZgbT… Memori… Maroon…      67 63rPSO… Memori… 2019-1… Pop Re… 37i9dQ…
3 1z1Hg7Vb0AhHD… All th… Zara L…      70 1HoSmj… All th… 2019-0… Pop Re… 37i9dQ…
4 75FpbthrwQmzH… Call Y… The Ch…      60 1nqYsO… Call Y… 2019-0… Pop Re… 37i9dQ…
5 1e8PAfcKUYoKk… Someon… Lewis …      69 7m7vv9… Someon… 2019-0… Pop Re… 37i9dQ…
6 7fvUMiyapMsRR… Beauti… Ed She…      67 2yiy9c… Beauti… 2019-0… Pop Re… 37i9dQ…
# … with 14 more variables: playlist_genre &lt;chr&gt;, playlist_subgenre &lt;chr&gt;,
#   danceability &lt;dbl&gt;, energy &lt;dbl&gt;, key &lt;dbl&gt;, loudness &lt;dbl&gt;, mode &lt;dbl&gt;,
#   speechiness &lt;dbl&gt;, acousticness &lt;dbl&gt;, instrumentalness &lt;dbl&gt;,
#   liveness &lt;dbl&gt;, valence &lt;dbl&gt;, tempo &lt;dbl&gt;, duration_ms &lt;dbl&gt;, and
#   abbreviated variable names ¹​track_name, ²​track_artist, ³​track_popularity,
#   ⁴​track_album_id, ⁵​track_album_name, ⁶​track_album_release_date,
#   ⁷​playlist_name, ⁸​playlist_id</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32833</code></pre>
</div>
</div>
</section>
<section id="results-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="results-and-analysis">Results and Analysis</h2>
<p>First we will plot out general popularity of songs versus their adaptability score. This will allow us to visualize how dance-ability affects song’s popularity overall in the data set.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/popularity-vs-danceability-general-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above plot we see a very subtle correlation between the danceability rating and its popularity for this random sampling of 1000 songs. However, with so many data points on this plot danceability likely is not a great predictor for track popularity <strong>generally</strong>. There is no significant linear relationship between danceability and popularity.</p>
<p>Next, we’d like to see what this plot looks like if we facet it by the genre.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/popularity-vs-danceability-genre-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we can see that there is certainly a difference in how dance-ability affects the popularity of a track depending on the songs genre. Our highest correlations found here are rap and pop while we even see a slightly decreasing slope for r&amp;b. However, its worth noting that some genres tend to have a higher dance-ability score on average such as Latin and rap. While rock has a higher correlation than some other genres, on average its songs are less dance-able than the others.</p>
<p>Now, we’d like to train a linear regression model to predict popularity using dance-ability. We’ll train three separate models here.</p>
<ol type="1">
<li><p>A general model that can be used for any genre</p></li>
<li><p>A model that predicts how dance-ability affects the popularity of a song from the Latin genre.</p></li>
<li><p>A model that predicts how dance-ability affects the popularity of a song from the rap genre</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,570
Columns: 23
$ track_id                 &lt;chr&gt; "0r7CVbZTWZgbTCYdfa2P31", "7fvUMiyapMsRRxr07c…
$ track_name               &lt;chr&gt; "Memories - Dillon Francis Remix", "Beautiful…
$ track_artist             &lt;chr&gt; "Maroon 5", "Ed Sheeran", "Loud Luxury", "AJ …
$ track_popularity         &lt;dbl&gt; 67, 67, 67, 60, 35, 87, 56, 34, 45, 48, 74, 7…
$ track_album_id           &lt;chr&gt; "63rPSO264uRjW1X5E6cWv6", "2yiy9cd2QktrNvWC2E…
$ track_album_name         &lt;chr&gt; "Memories (Dillon Francis Remix)", "Beautiful…
$ track_album_release_date &lt;chr&gt; "2019-12-13", "2019-07-11", "2019-03-29", "20…
$ playlist_name            &lt;chr&gt; "Pop Remix", "Pop Remix", "Pop Remix", "Pop R…
$ playlist_id              &lt;chr&gt; "37i9dQZF1DXcZDD7cfEKhW", "37i9dQZF1DXcZDD7cf…
$ playlist_genre           &lt;chr&gt; "pop", "pop", "pop", "pop", "pop", "pop", "po…
$ playlist_subgenre        &lt;chr&gt; "dance pop", "dance pop", "dance pop", "dance…
$ danceability             &lt;dbl&gt; 0.726, 0.675, 0.744, 0.694, 0.467, 0.693, 0.7…
$ energy                   &lt;dbl&gt; 0.815, 0.919, 0.726, 0.901, 0.821, 0.678, 0.8…
$ key                      &lt;dbl&gt; 11, 8, 1, 1, 7, 8, 0, 1, 7, 11, 6, 9, 7, 5, 7…
$ loudness                 &lt;dbl&gt; -4.969, -5.385, -4.675, -4.322, -5.466, -7.15…
$ mode                     &lt;dbl&gt; 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, …
$ speechiness              &lt;dbl&gt; 0.0373, 0.1270, 0.0463, 0.0948, 0.0934, 0.032…
$ acousticness             &lt;dbl&gt; 0.072400, 0.079900, 0.039900, 0.070200, 0.007…
$ instrumentalness         &lt;dbl&gt; 4.21e-03, 0.00e+00, 0.00e+00, 0.00e+00, 4.41e…
$ liveness                 &lt;dbl&gt; 0.3570, 0.1430, 0.3740, 0.4270, 0.1310, 0.101…
$ valence                  &lt;dbl&gt; 0.693, 0.585, 0.687, 0.368, 0.232, 0.404, 0.4…
$ tempo                    &lt;dbl&gt; 99.972, 124.982, 121.985, 118.051, 122.676, 1…
$ duration_ms              &lt;dbl&gt; 162600, 163049, 192507, 173548, 185366, 22826…</code></pre>
</div>
</div></li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)      35.3     0.712      49.6 0       
2 danceability     10.9     1.06       10.3 7.43e-25</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     41.3       2.50     16.5  3.80e-59
2 danceability     7.94      3.46      2.30 2.18e- 2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term         estimate std.error statistic  p.value
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)      25.9      1.84     14.1  3.03e-44
2 danceability     24.0      2.51      9.54 2.20e-21</code></pre>
</div>
</div>
<p><span class="math inline">\(pop_{general} = 35.3 + 10.9 * danceability\)</span></p>
<p>For a 1 increase in danceability rating, there’s an estimated mean change of a song’s popularity rating (general song w/ no designated genre) by 11.1.</p>
<p>When danceability is 0, there is an estimated mean popularity rating of 35.2.</p>
<p><span class="math inline">\(pop_{latin} = 41.3 + 7.94 * danceability\)</span></p>
<p>For a 1 increase in danceability rating, there’s an estimated mean change of a latin song’s popularity rating by up by 8.8.</p>
<p>When danceability is 0, there is an estimated mean popularity rating of 40.7.</p>
<p><span class="math inline">\(pop_{rap} = 35.3 + 10.9 * danceability\)</span></p>
<p>For a 1 increase in danceability rating, there’s an estimated mean change of a song’s popularity rating by 11.2.</p>
<p>When danceability is 0, there is an estimated mean popularity rating of 25.5.</p>
<p><strong>Training Data Set</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 623.7248</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 647.9394</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 539.8089</code></pre>
</div>
</div>
<p><strong>Testing Data Set</strong></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pop_pred_general - test_data$track_popularity: longer object length
is not a multiple of shorter object length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 618.2059</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 634.6527</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 498.709</code></pre>
</div>
</div>
<p><strong>MSE Table</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 6
$ general_dance_train &lt;dbl&gt; 623.7248
$ general_dance_test  &lt;dbl&gt; 618.2059
$ latin_dance_train   &lt;dbl&gt; 647.9394
$ latin_dance_test    &lt;dbl&gt; 634.6527
$ rap_dance_train     &lt;dbl&gt; 539.8089
$ rap_dance_test      &lt;dbl&gt; 498.709</code></pre>
</div>
</div>
<p><strong>Model Fit Assessments</strong></p>
<p>Now we’d like to assess how well the regression model explains the observed data. We will do this by calculating adjusted R squared values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003989811</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00103406</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01922207</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 3
$ R2_general_dance &lt;dbl&gt; 0.00416193
$ R2_latin_dance   &lt;dbl&gt; 0.001381617
$ R2_rap_dance     &lt;dbl&gt; 0.02070946</code></pre>
</div>
</div>
<p>Based on the adjusted R squared values, danceability rating as an explanatory variable is not a good predictor of popularity rating in general and in the latin and rap genres. The adjusted R squared values between 0.14-4.2% reveals a very low variability in popularity is explained by the regression model.</p>
<p>Now we’d like to assess how well the regression model explains the observed data using AIC and an ROC curve.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `pull(glance(general_dance), AIC)`
                               &lt;dbl&gt;
1                            243558.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `pull(glance(latin_dance), AIC)`
                             &lt;dbl&gt;
1                           38407.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `pull(glance(rap_dance), AIC)`
                           &lt;dbl&gt;
1                         41963.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 3
$ AIC_general_dance &lt;dbl&gt; 304371.9
$ AIC_latin_dance   &lt;dbl&gt; 47986.36
$ AIC_rap_dance     &lt;dbl&gt; 52373.25</code></pre>
</div>
</div>
<p>Based on AIC calculations, the general model was best fit because it had the lowest AIC value at 304371.9, where the latin model had an AIC of 47986.36 and rap model had an AIC of 52373.25. AIC selects a model with the least mean squared error, so a lower value is preferable ^[http://www.sthda.com/english/articles/38-regression-model-validation/158-regression-model-accuracy-metrics-r-square-aic-bic-cp-and-more/].</p>
<p><strong>Multiple Linear Regression Models</strong></p>
<p>Now, we’d like to train multiple linear regression models to predict popularity using dance-ability, tempo, and energy. We’ll train multiple separate models.</p>
<ol type="1">
<li>An additive model for danceability rating + tempo.</li>
<li>An additive model for danceability rating + energy.</li>
<li>An additive model for danceability rating + tempo + energy.</li>
<li>An interaction model for danceability rating * tempo.</li>
<li>An interaction model for danceability rating * energy.</li>
<li>An interaction model for danceability rating * tempo * energy.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 304372.5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 304015.9</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 304003.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 304374.2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 304012.7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 303995.3</code></pre>
</div>
</div>
<p>Given that the interaction model between danceability rating, tempo, and energy resulted in the lowest AIC value (303995.3), it is the best fit of the ones assessed at modeling popularity of a song. We excluded genre in the multiple-linear regression models, because we learned that genre did not have significant impacts on our previous predictive models. This caused us to shift our focus to other variables that could potentially impact our predicative models.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 6
$ AIC_dance_plus_tempo        &lt;dbl&gt; 304372.5
$ AIC_dance_plus_energy       &lt;dbl&gt; 304015.9
$ AIC_dance_plus_tempo_energy &lt;dbl&gt; 304003.1
$ AIC_dance_int_tempo         &lt;dbl&gt; 304374.2
$ AIC_dance_int_energy        &lt;dbl&gt; 304012.7
$ AIC_dance_int_tempo_energy  &lt;dbl&gt; 303995.3</code></pre>
</div>
</div>
</section>
<section id="overall-results-next-steps-limitations-discussion" class="level2">
<h2 class="anchored" data-anchor-id="overall-results-next-steps-limitations-discussion">Overall Results + Next Steps + Limitations (DISCUSSION)</h2>
<ol type="1">
<li><p>Danceability is not a great predictor for popularity when <strong>not</strong> faceted by genre.</p></li>
<li><p>Danceability has different impacts on popularity when faceted by genre.</p></li>
<li><p>Danceability has a positive and significant effect on popularity ratings of general, latin, and rap songs. This relationship varies</p>
<ol type="1">
<li><p>Rap has the highest coefficient</p></li>
<li><p>General has the lowest</p></li>
</ol></li>
<li><p>General model had best fit according to AIC criteria (lowest mean squared error)</p></li>
<li><p>The interactive model for danceability * tempo * energy has lowest AIC</p></li>
<li><p>The additive and interactive models that included the energy variable had lower AIC values</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>